projects/yii2.loc/models/Category.php
<?php
/**
 * Created by PhpStorm.
 * User: Andrey
 * Date: 07.05.2016
 * Time: 10:28
 */

namespace app\models;
use yii\db\ActiveRecord;

error_reporting(E_ALL);

class Category extends ActiveRecord{

	public function behaviors()
    {
        return [
            'image' => [
                'class' => 'rico\yii2images\behaviors\ImageBehave',
            ]
        ];
    }

    public static function tableName(){
        return 'category';
    }
/*т.к. в одной категории может сод.много товаров то
это связь одного к hasMany*/
/* 2 парам. указ. по какому полю осущ.данная связь*/
/* => на какое поле ссылается данное поле в табл.*/
    public function getProducts(){
        return $this->hasMany(Product::className(), ['category_id' => 'id']);
    }

} 

projects/yii2.loc/controllers/CategoryController.php
<?php


namespace app\controllers;
use app\models\Category;
use app\models\Product;
use Yii;
use yii\data\Pagination;

class CategoryController extends AppController{

    public function actionIndex(){
    	//где поле hit = 1 в '' т.к. тип поля в базе enum текст,
    	// если integer то без '' limit 6 как в макете
        $hits = Product::find()->where(['hit' => '1'])->limit(6)->all();
        // вызываем метод и уст.название 
        $this->setMeta('E-SHOPPER');
        //массив hits доступен в шаблоне теперь пройдемся в цикле
        return $this->render('index', compact('hits'));
    }
    /* id - принимает числовой парам из п.51 config/web   'category/<id:\d+>' => 'category/view',*/
    // просмотр категорий
    // 1 вар. получение парам.из роутов config/web п.52
     public function actionView($id){
     	// 2 вар.получения id из arr get т.е. из адресной стр.
        //$id = Yii::$app->request->get('id');
        // данные для категории
        $category = Category::findOne($id);
        // если пуст arr category
         if(empty($category))
            throw new \yii\web\HttpException(404, 'Такой категории нет');
        //debug($id);
        //получаем продукты по номеру id
        // обращаемся к модели prodact задаем усл. где поле кат.id в табл. продуктов = текущему переданному id
        //$products = Product::find()->where(['category_id' => $id])->all();
        //создаем объект запроса для пагинации
         $query = Product::find()->where(['category_id' => $id]);
         //создаем объект класса pagination к методу tc который посчитает кол-во записей. ук. парам.pageSize и нужное кол-во для вывода. 
         $pages = new Pagination(['totalCount' => $query->count(), 'pageSize' => 3, 'forcePageParam' => false, 'pageSizeParam' => false]);
         // выполняем запрос с какой записи и сколько
         $products = $query->offset($pages->offset)->limit($pages->limit)->all();

       
        // выводим title E-SHOPPER и прицепляем название категории
         $this->setMeta('E-SHOPPER | ' . $category->name, $category->keywords, $category->description);

        // рендерим category/view и передаем в него найденные продукты
        return $this->render('view', compact('products', 'pages', 'category'));
    }

     public function actionSearch(){
     	// получаем запрос из адресной стр.
        $q = trim(Yii::$app->request->get('q'));
        //находим данные по этому запросу
        // формирование title
        $this->setMeta('E-SHOPPER | Поиск: ' . $q);
        // если в запросе ничего нет, то ничего не выведет
        if(!$q)
            return $this->render('search');
        // оператор like поле name = query
        $query = Product::find()->where(['like', 'name', $q]);
        $pages = new Pagination(['totalCount' => $query->count(), 'pageSize' => 3, 'forcePageParam' => false, 'pageSizeParam' => false]);
        $products = $query->offset($pages->offset)->limit($pages->limit)->all();
        // вид search перем.prodacts pages q
        return $this->render('search', compact('products', 'pages', 'q'));
    }

} 

projects/yii2.loc/controllers/ProductController.php
<?php
/**
 * Created by PhpStorm.
 * User: Andrey
 * Date: 09.05.2016
 * Time: 10:50
 */
// вывод карточки товара
namespace app\controllers;
use app\models\Category;
use app\models\Product;
use Yii;

class ProductController extends AppController{
//получаем id продукта из arr get
    public function actionView($id){
        $id = Yii::$app->request->get('id');
        // получаем из бд dc. всю инфу по товару и инфу о кат.
        // 1 вар. ленивая загрузка 
        $product = Product::findOne($id);
         if(empty($product))
            throw new \yii\web\HttpException(404, 'Такого товара нет');
//        $product = Product::find()->with('category')->where(['id' => $id])->limit(1)->one();
        // 2 вар. жадная загрузка в with - та связь кот. указ. в модели
//        $product = Product::find()->with('category')->where(['id' => $id])->limit(1)->one();
        //получаем все из табл.продуктов где поле хит =1 передаём их в render
        $hits = Product::find()->where(['hit' => '1'])->limit(6)->all();
        //title в назв.стр.
        $this->setMeta('E-SHOPPER | ' . $product->name, $product->keywords, $product->description);
        // возвр.шаблон с парам. объекта product
        return $this->render('view', compact('product','hits'));
    }

} 

projects/yii2.loc/views/category/search.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;
?>
<section id="advertisement">
    <div class="container">
        <img src="/images/shop/1.jpg" alt="" />
    </div>
</section>

<section>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <div class="left-sidebar">
                    <h2>Category</h2>
                    <ul class="catalog category-products">
                        <?= \app\components\MenuWidget::widget(['tpl' => 'menu'])?>
                    </ul>

                    <div class="brands_products"><!--brands_products-->
                        <h2>Brands</h2>
                        <div class="brands-name">
                            <ul class="nav nav-pills nav-stacked">
                                <li><a href=""> <span class="pull-right">(50)</span>Acne</a></li>
                                <li><a href=""> <span class="pull-right">(56)</span>Grüne Erde</a></li>
                                <li><a href=""> <span class="pull-right">(27)</span>Albiro</a></li>
                                <li><a href=""> <span class="pull-right">(32)</span>Ronhill</a></li>
                                <li><a href=""> <span class="pull-right">(5)</span>Oddmolly</a></li>
                                <li><a href=""> <span class="pull-right">(9)</span>Boudestijn</a></li>
                                <li><a href=""> <span class="pull-right">(4)</span>Rösch creative culture</a></li>
                            </ul>
                        </div>
                    </div><!--/brands_products-->

                    <div class="price-range"><!--price-range-->
                        <h2>Price Range</h2>
                        <div class="well">
                            <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
                            <b>$ 0</b> <b class="pull-right">$ 600</b>
                        </div>
                    </div><!--/price-range-->

                    <div class="shipping text-center"><!--shipping-->
                        <img src="/images/home/shipping.jpg" alt="" />
                    </div><!--/shipping-->

                </div>
            </div>

            <div class="col-sm-9 padding-right">
                <div class="features_items"><!--features_items-->
                    <h2 class="title text-center">Поиск по запросу: <?= Html::encode($q)?></h2>
                    <?php if(!empty($products)): ?>
                        <?php $i = 0; foreach($products as $product): ?>
                            <div class="col-sm-4">
                                <div class="product-image-wrapper">
                                    <div class="single-products">
                                        <div class="productinfo text-center">
                                            <?= Html::img("@web/images/products/{$product->img}", ['alt' => $product->name])?>
                                            <h2>$<?= $product->price?></h2>
                                            <p><a href="<?= \yii\helpers\Url::to(['product/view', 'id' => $product->id]) ?>"><?= $product->name?></a></p>
                                            <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                                        </div>
                                        <?php if($product->new): ?>
                                            <?= Html::img("@web/images/home/new.png", ['alt' => 'Новинка', 'class' => 'new'])?>
                                        <?php endif?>
                                        <?php if($product->sale): ?>
                                            <?= Html::img("@web/images/home/sale.png", ['alt' => 'Распродажа', 'class' => 'new'])?>
                                        <?php endif?>
                                    </div>
                                    <div class="choose">
                                        <ul class="nav nav-pills nav-justified">
                                            <li><a href=""><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                                            <li><a href=""><i class="fa fa-plus-square"></i>Add to compare</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <?php $i++?>
                            <?php if($i % 3 == 0): ?>
                                <div class="clearfix"></div>
                            <?php endif;?>
                        <?php endforeach;?>
                        <div class="clearfix"></div>
                        <?php
                        echo \yii\widgets\LinkPager::widget([
                            'pagination' => $pages,
                        ]);
                        ?>
                    <?php else :?>
                        <h2>Ничего не найдено...</h2>
                    <?php endif;?>
                </div><!--features_items-->
            </div>
        </div>
    </div>
</section>

projects/yii2.loc/views/category/view.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;
?>
<section id="advertisement">
    <div class="container">
        <img src="/images/shop/1.jpg" alt="" />
    </div>
</section>

<section>
<div class="container">
<div class="row">
<div class="col-sm-3">
    <div class="left-sidebar">
        <h2>Category</h2>
        <ul class="catalog category-products">
        <!--вставляем наш виджет -->
            <?= \app\components\MenuWidget::widget(['tpl' => 'menu'])?>
        </ul>

        <div class="brands_products"><!--brands_products-->
            <h2>Brands</h2>
            <div class="brands-name">
                <ul class="nav nav-pills nav-stacked">
                    <li><a href=""> <span class="pull-right">(50)</span>Acne</a></li>
                    <li><a href=""> <span class="pull-right">(56)</span>Grüne Erde</a></li>
                    <li><a href=""> <span class="pull-right">(27)</span>Albiro</a></li>
                    <li><a href=""> <span class="pull-right">(32)</span>Ronhill</a></li>
                    <li><a href=""> <span class="pull-right">(5)</span>Oddmolly</a></li>
                    <li><a href=""> <span class="pull-right">(9)</span>Boudestijn</a></li>
                    <li><a href=""> <span class="pull-right">(4)</span>Rösch creative culture</a></li>
                </ul>
            </div>
        </div><!--/brands_products-->

        <div class="price-range"><!--price-range-->
            <h2>Price Range</h2>
            <div class="well">
                <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
                <b>$ 0</b> <b class="pull-right">$ 600</b>
            </div>
        </div><!--/price-range-->

        <div class="shipping text-center"><!--shipping-->
        <!-- меняем картинки на абсолютный путь img scr =" на img src="/ -->
            <img src="/images/home/shipping.jpg" alt="" />
        </div><!--/shipping-->

    </div>
</div>

<div class="col-sm-9 padding-right">
<div class="features_items"><!--Название категории-->
<h2 class="title text-center"><?= $category->name?></h2>
<!-- если нет товара т.е. не пусто в массиве prodacts то не выводим -->
    <?php if(!empty($products)): ?>
        <!-- запускаем счетчик, чтобы выровнять товары 2 способ после каждого 3 товара ставить класс row -->
        <?php $i = 0; foreach($products as $product): ?>
        <?php $mainImg = $product->getImage();?>
<div class="col-sm-4">
   <div class="product-image-wrapper">
        <div class="single-products">
            <div class="productinfo text-center">
                <!--картинка -->
                 <?= Html::img($mainImg->getUrl('268x249'), ['alt' => $product->name])?>
                 <!--цена -->
                <h2>$<?= $product->price?></h2>
                <p><a href="<?= \yii\helpers\Url::to(['product/view', 'id' => $product->id]) ?>"><?= $product->name?></a></p>
                <!--ссылка для корзины-->
                <a href="#" data-id="<?= $product->id?>" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
            </div>
             <!-- вместо hit  product -->
          
            <?php if($product->new): ?>
                <?= Html::img("@web/images/home/new.png", ['alt' => 'Новинка', 'class' => 'new'])?>
            <?php endif?>
            <?php if($product->sale): ?>
                <?= Html::img("@web/images/home/sale.png", ['alt' => 'Распродажа', 'class' => 'new'])?>
            <?php endif?>
        </div>
        <div class="choose">
            <ul class="nav nav-pills nav-justified">
                <li><a href=""><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                <li><a href=""><i class="fa fa-plus-square"></i>Add to compare</a></li>
            </ul>
        </div>
    </div>
</div>
      <!-- после выведенного товара ув.счетчик и когда он достигнет 3 то добавится блок с классом clearfix-->
            <?php $i++?>
            <!-- если пер.i делится на 3 без остатка -->
            <?php if($i % 3 == 0): ?>
                <!-- добавляем блок с классом -->
                <div class="clearfix"></div>
            <?php endif;?>
            <!--конец цикла foreach-->
            <?php endforeach;?>
             <div class="clearfix"></div>
        <?php
        echo \yii\widgets\LinkPager::widget([
            'pagination' => $pages,
        ]);
        ?>
        <?php else :?>
        <h2>Здесь товаров пока нет...</h2>
    <?php endif;?>
<!--<ul class="pagination">
    <li class="active"><a href="">1</a></li>
    <li><a href="">2</a></li>
    <li><a href="">3</a></li>
    <li><a href="">&raquo;</a></li>
</ul>-->
</div><!--features_items-->
</div>
</div>
</div>
</section>